energy_empty = 'queryimages\#\energy_empty.png'
get_button = 'queryimages\#\get_button.png'
next_button = 'queryimages\#\\next_button.png'
no_button = 'queryimages\#\\no_button.png'
no_stage_button = 'queryimages\#\\no_stage_button.png'
ok_button = 'queryimages\#\ok_button.png'
replay_button = 'queryimages\#\\replay_button.png'
screen_defeated = 'queryimages\#\screen_defeated.png'
screen_victory = 'queryimages\#\screen_victory.png'
screen_clear = 'queryimages\#\screen_clear.png'
sell_button = 'queryimages\#\sell_button.png'
start_button = 'queryimages\#\start_button.png'
yes_button = 'queryimages\#\yes_button.png'

bot_action = 'Choose:\n1- Sell Items\n2- Take Items\n3- TOA Run\n4- SD Farm\n'